name: movies
description: A new Flutter project.
publish_to: "none"
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  dio: ^3.0.10
  intl: ^0.16.1
  flutter_launcher_icons: ^0.8.1
  custom_splash: ^0.0.2
  fancy_shimmer_image: ^1.2.0
  infinite_scroll_pagination: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - movie-splash.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/pipoca.ico"
